#ifndef _HSK_ERRORS_H
#define _HSK_ERRORS_H

// Generic
#define HSK_SUCCESS 0
#define HSK_EOK 0
#define HSK_ENOMEM 1
#define HSK_ETIMEOUT 2
#define HSK_EFAILURE 3
#define HSK_EBADARGS 4
#define HSK_EENCODING 5

// Proofs
#define HSK_EPROOFOK 0
#define HSK_EHASHMISMATCH 6
#define HSK_ESAMEKEY 7
#define HSK_ESAMEPATH 8
#define HSK_ENEGDEPTH 9
#define HSK_EPATHMISMATCH 10
#define HSK_ETOODEEP 11
#define HSK_EUNKNOWNERROR 12
#define HSK_EMALFORMEDNODE 13
#define HSK_EINVALIDNODE 14
#define HSK_EEARLYEND 15
#define HSK_ENORESULT 16
#define HSK_EUNEXPECTEDNODE 17
#define HSK_ERECORDMISMATCH 18

// Cuckoo
#define HSK_EPOWOK 0
#define HSK_EPOWPROOFSIZE 19
#define HSK_EPOWTOOBIG 20
#define HSK_EPOWTOOSMALL 21
#define HSK_EPOWNONMATCHING 22
#define HSK_EPOWBRANCH 23
#define HSK_EPOWDEADEND 24
#define HSK_EPOWSHORTCYCLE 25

// POW
#define HSK_ENEGTARGET 26
#define HSK_EHIGHHASH 27

// Chain
#define HSK_ETIMETOONEW 28
#define HSK_EDUPLICATE 29
#define HSK_EDUPLICATEORPHAN 30
#define HSK_ETIMETOOOLD 31
#define HSK_EBADDIFFBITS 32
#define HSK_EORPHAN 33

// Brontide
#define HSK_EACTONE 34
#define HSK_EACTTWO 35
#define HSK_EACTTHREE 36
#define HSK_EBADSIZE 37
#define HSK_EBADTAG 38

// Max
#define HSK_MAXERROR 39

const char *
hsk_strerror(int code);

#endif
