name: libhsk mainnet

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ubuntu Install Deps
        run: sudo apt-get update && sudo apt-get install -y

      - name: Build
        run: |
          ./autogen.sh
          ./configure --without-daemon
          make
          sudo make install
          make test_libhsk

      - name: libhsk mainnet test
        run: ./test_libhsk
