name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: MacOS Install Deps
        if: matrix.os == 'macos-latest'
        run: brew install automake autoconf libtool unbound

      - name: Ubuntu Install Deps
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libunbound-dev

      - name: Build
        run: ./autogen.sh && ./configure --with-network=regtest && make

      - name: Unit Tests
        run: ./test_hnsd

      - name: Setup Integration
        uses: actions/setup-node@v1

      - name: Integration Tests
        working-directory: ./test/integration
        run:  |
              npm install
              ./node_modules/bmocha/bin/bmocha --reporter spec hnsd-integration-test.js
